CREATE DATABASE ECOLE_PRIMAIRE

=====================CREATION DEES TABLESS =========================================================================================================

CREATE TABLE ANNE_SCOLAIRE(
ID INT IDENTITY PRIMARY KEY,
DESIGNATION VARCHAR(9)
)

SELECT DESIGNATION FROM ANNE_SCOLAIRE WHERE ID=(SELECT MAX(ID) FROM ANNE_SCOLAIRE)

CREATE TABLE DETAILS_ANNE_SCOLAIRE(
ID_ANNE INT PRIMARY KEY,
DEBUT_DATE DATE DEFAULT GETDATE()
)




CREATE TABLE LISTE_DE_SANCTION(
 ID INT IDENTITY PRIMARY KEY,
 DESIGNATION VARCHAR(25) NOT NULL,
 PONDERATION INT,
)

CREATE TABLE NIVEAU_ETUDE(
NIVEAU INT PRIMARY KEY
)

SELECT SALLE.NIVEAU_ETUDE,SECTION.DESIGNATION,ABREVIATION,DESIGNATION_SALLE.LETTRE,DESIGNATION_SALLE.NOMBRE_PLACE,CONCAT(AGENT.NOM,' ',AGENT.POSTNOM,' ',PRENOM) AS TITULAIRE FROM SALLE INNER JOIN DESIGNATION_SALLE on SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON  SALLE.SECTION=SECTION.ID INNER JOIN TITULARISATION_SALLE ON TITULARISATION_SALLE.SALLE=DESIGNATION_SALLE.ID INNER JOIN  AGENT ON AGENT.MATRICULE=TITULARISATION_SALLE.AGENT

SELECT * from NIVEAU_ETUDE 

SELECT * FROM NIVEAU_ETUDE
INSERT INTO NIVEAU_ETUDE(NIVEAU) VALUES(1)
CREATE TABLE SECTION(
ID INT IDENTITY PRIMARY KEY,
DESIGNATION VARCHAR(15)
)
select NOM,POSTNOM,PRENOM FROM AGENT
SELECT MIN(NIVEAU),MAX(NIVEAU) FROM NIVEAU_ETUDE
-------------------------------------MODIFICATION SECTION
ALTER TABLE SECTION ADD ABREVIATION VARCHAR(5) NOT NULL
ALTER TABLE SECTION ALTER COLUMN DESIGNATION VARCHAR(30) NOT NULL
---------------------------------------------------------
CREATE TABLE SALLE(
ID INT IDENTITY PRIMARY KEY,
SECTION INT NOT NULL,
NIVEAU_ETUDE INT NOT NULL,
NOMBRE_PLACE INT NOT NULL
)
ALTER TABLE SALLE DROP COLUMN NOMBRE_PLACE
CREATE TABLE DESIGNATION_SALLE(
ID_SALLE INT,
LETTRE VARCHAR(1)
)
SELECT * FROM DESIGNATION_SALLE
UPDATE DESIGNATION_SALLE SET DISPONIBILITE=2
ALTER TABLE DESIGNATION_SALLE ADD  ID INT IDENTITY PRIMARY KEY
ALTER TABLE DESIGNATION_SALLE ADD NOMBRE_PLACE INT
ALTER TABLE DESIGNATION_SALLE ADD DISPONIBILITE INT DEFAULT 1
CREATE TABLE FRAIS_INSCRIPTION(
ID INT IDENTITY PRIMARY KEY,
SALLE INT,
ANNE_ACADEMIQUE INT,
MONTANT INT
)

CREATE TABLE INSCRIPTION_ELEVE(
ID INT IDENTITY PRIMARY KEY,
MATRICULE VARCHAR(10) NOT NULL UNIQUE,
SALLE INT,
DESIGNATION_SALLE INT,
)
ALTER TABLE INSCRIPTION_ELEVE DROP COLUMN DESIGNATION_SALLE
CREATE TABLE DETAILS_INSCRIPTION(
ID_INSCRIPTION INT,
HEURE TIME DEFAULT CONVERT(VARCHAR(30),GETDATE(),108),
DATE DATE DEFAULT CONVERT(VARCHAR(30),GETDATE(),103),
AGENT INT,
ANNE INT
)
alter table DETAILS_INSCRIPTION ALTER COLUMN ANNE INT DEFAULT 5 (SELECT MAX(ID) FROM ANNE_SCOLAIRE) 

SELECT FORMAT(GETDATE(),'yyyy-MM-dd')

CREATE TABLE PAIEMENT_FRAIS_INSCRIPTION(
ID INT IDENTITY PRIMARY KEY,
ID_INSCRIPTION INT,
MONTANT INT
)

CREATE TABLE DETAILS_PAIEMENT_INSCRIPTION(
ID_PAIEMENT_FRAIS_INSCRIPTION INT,
HEURE TIME DEFAULT CONVERT(VARCHAR(30),GETDATE(),108),
DATE DATE DEFAULT CONVERT(VARCHAR(30),GETDATE(),103),
AGENT INT
)


CREATE TABLE ELEVE(
ID INT IDENTITY PRIMARY KEY,
MATRICULE VARCHAR(10) NOT NULL UNIQUE,
NOM VARCHAR(15) NOT NULL,
POSTNOM VARCHAR(15) NOT NULL,
PRENOM VARCHAR(15) NOT NULL,
DATE DATE NOT NULL,
PHOTO IMAGE
)

CREATE TABLE ADDRESSE_ELEVE(
MATRICULE VARCHAR(10) PRIMARY KEY,
PAYS VARCHAR(15) NOT NULL,
PROVINCE VARCHAR(15) NOT NULL,
VILLE VARCHAR(15) NOT NULL,
QUARTIER VARCHAR(15) NOT NULL,
NUMERO INT
)
CREATE TABLE COORDONNES_ELEVE(
MATRICULE_ELEVE VARCHAR(10),
EMAIL VARCHAR(35),
CELULAIRE VARCHAR(14)
)

CREATE TABLE TUTEUR(
ID INT IDENTITY PRIMARY KEY,
MATRICULE_ELEVE VARCHAR(10),
NOM VARCHAR(15) NOT NULL,
POSTNOM VARCHAR(15) NOT NULL,
PRENOM VARCHAR(15) NOT NULL,
)

CREATE TABLE COORDONNES_TUTEUR(
ID INT PRIMARY KEY,
EMAIL VARCHAR(35),
CELULAIRE VARCHAR(14)
)


CREATE TABLE COURS(
ID INT IDENTITY PRIMARY KEY,
DESIGNATION VARCHAR(15) NOT NULL,
)

CREATE TABLE HORAIRE(
ID INT IDENTITY PRIMARY KEY,
SALLE INT,
ANNE INT,
PONDERATION INT,
PROF INT
)

ALTER TABLE HORAIRE ADD NOMBRE_JOURNALIER INT

CREATE TABLE AFFECTATION_COURS(
ID INT IDENTITY PRIMARY KEY,
HORAIRE INT,
DESIGNATION_SALLE INT,
PROF VARCHAR(10)
)

ALTER TABLE HORAIRE DROP COLUMN PROF

ALTER TABLE HORAIRE ALTER COLUMN PROF VARCHAR(10)
ALTER TABLE HORAIRE ADD COURS INT

CREATE TABLE TRAVAIL(
ID INT IDENTITY PRIMARY KEY,
COURS INT,
PROF INT,
DENOMINATION VARCHAR(25) NOT NULL,
)

ALTER TABLE TRAVAIL ADD DESIGNATION_SALLE INT
ALTER TABLE TRAVAIL alter column prof varchar(10)
CREATE TABLE SANCTION(
ID INT IDENTITY PRIMARY KEY,
MATRICULE_ELEVE VARCHAR(10),
MOTIF INT,
)

CREATE TABLE DETAILS_SANCTION(
ID INT PRIMARY KEY,
HEURE TIME DEFAULT CONVERT(VARCHAR(30),GETDATE(),108),
DATE DATE DEFAULT CONVERT(VARCHAR(30),GETDATE(),103),
ANNE INT,
PERIODE INT,
AGENT INT
)

create TABLE DETAILS_TRAVAIL(
ID INT PRIMARY KEY,
HEURE TIME DEFAULT CONVERT(VARCHAR(30),GETDATE(),108),
DATE DATE DEFAULT FORMAT(GETDATE(),'yyyy-MM-dd'),
MOTIF INT,
MAXIMUM INT,
ANNE INT,
PERIODE INT
)

SELECT FORMAT(GETDATE(),'yyyy-MM-dd')

CREATE TABLE MOTIF_INTERROGATION(
ID INT IDENTITY PRIMARY KEY,
DESIGNATION VARCHAR(30) NOT NULL
)

CREATE TABLE COTATION(
ID INT IDENTITY PRIMARY KEY,
ID_TRAVAIL INT,
MATRICULE_ELEVE VARCHAR(10) NOT NULL,
POINT INT
)

CREATE TABLE DETAILS_COTATION(
ID_COTATION INT,
HEURE TIME DEFAULT CONVERT(VARCHAR(30),GETDATE(),108),
DATE DATE DEFAULT CONVERT(VARCHAR(30),GETDATE(),103),
AGENT INT
)

CREATE TABLE BULLETIN(
ID INT IDENTITY PRIMARY KEY,
MATRICULE_ELEVE VARCHAR(10),
PERIODE INT,
COURS INT,
POINT INT,
ANNE INT
)

CREATE TABLE INSCRIPTION_AGENT
(
ID INT IDENTITY PRIMARY KEY,
MATRICULE VARCHAR(10) UNIQUE,
DEPARTEMENT INT
)

CREATE TABLE DETAIL_INSCRIPTION_AGENT
(
ID_INSCRIPTION_AGENT INT PRIMARY KEY,
HEURE TIME DEFAULT  CONVERT(time,GETDATE(),108),
DATE DATE DEFAULT CONVERT(date,GETDATE(),103),
AGENT INT
)

/*======================================modifier table dtails=================*/

alter table DETAIL_INSCRIPTION_AGENT alter column HEURE TIME DEFAULT  CONVERT(time,GETDATE(),108)



CREATE TABLE DEPARTEMENT(
ID INT IDENTITY PRIMARY KEY,
DESIGNATION VARCHAR(15) NOT NULL
)

CREATE TABLE SALAIRE(
ID_DEPARTEMENT INT PRIMARY KEY,
MONTANT INT
)

CREATE TABLE AVANTAGE(
ID INT IDENTITY PRIMARY KEY,
ID_DEPARTEMENT INT,
DESIGNATION VARCHAR(25) NOT NULL,
MONTANT INT
)

CREATE TABLE DOSSIER_SCOLAIRE_AGENT(
ID INT IDENTITY PRIMARY KEY,
NIVEAU_ETUDE VARCHAR(15) NOT NULL,
ANNE DATE,
POURCENTAGE INT,
)

CREATE TABLE AGENT(
MATRICULE VARCHAR(10) PRIMARY KEY,
NOM VARCHAR(25),
POSTNOM VARCHAR(25),
PRENOM VARCHAR(25),
DATE DATE,
PHOTO IMAGE
)
SELECT CONCAT(NOM,' ',POSTNOM,' ',PRENOM) FROM AGENT
CREATE TABLE ADDRESSE_AGENT(
MATRICULE VARCHAR(10) PRIMARY KEY,
TELEPHONE VARCHAR(10),
VILLE VARCHAR(15),
QUARTIER VARCHAR(15),
AVENU VARCHAR(15),
NUMERO INT
)

select TOP 1 PHOTO from AGENT
CREATE TABLE QR_AGENT_PRESENCE(
ID INT IDENTITY PRIMARY KEY,
MATRICULE_AGENT VARCHAR(10)
)

CREATE TABLE DETAILS_QR_AGENT_PRESENCE(
ID_QR_AGENT_PRESENCE INT PRIMARY KEY,
HEURE TIME DEFAULT CONVERT(VARCHAR(30),GETDATE(),108),
DATE DATE DEFAULT CONVERT(VARCHAR(30),GETDATE(),103),
PERIODE INT,
ANNE INT,
)


CREATE TABLE MOTIF_PAIEMENT(
ID INT IDENTITY PRIMARY KEY,
DESIGNATION VARCHAR(25) NOT NULL,
MONTANT INT NOT NULL
)

CREATE TABLE TITULARISATION_SALLE(
ID INT IDENTITY PRIMARY KEY,
SALLE INT,
AGENT VARCHAR(10),
ANNE INT
)
CREATE TABLE PROGRAMME_JOURNE(
JOUR VARCHAR(10) PRIMARY KEY,
NOMBRE_HEURE INT,
MINUTE_HEURE INT
)



CREATE TABLE PROGRAMME_ENSEIGNEMENT
(

ID INT PRIMARY KEY IDENTITY,
JOUR VARCHAR(10),
AFFECTATION INT,
HEURE INT
)

create table periode(
id int identity primary key,
designation varchar(10),
date date default  format(getdate(),'yyyy-MM-dd'),
anne int 
)
SELECT DESIGNATION FROM PERIODE WHERE ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE)
create proc perioder
(
@designation varchar(10)
)
as
begin
	declare @anne int;
	select @anne=max(id) from ANNE_SCOLAIRE
	insert into periode(designation,anne)values(@designation,@anne)
end

SELECT * from periode

SELECT * FROM PROGRAMME_ENSEIGNEMENT
ALTER TABLE PROGRAMME_ENSEIGNEMENT drop column affectation
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD LUNDI INT
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD LUNDI INT
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD MARDI INT
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD MERCREDI INT
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD JEUDI INT
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD VENDREDI INT
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD SAMEDI INT

DELETE FROM PROGRAMME_ENSEIGNEMENT

SELECT * FROM PROGRAMME_ENSEIGNEMENT

SELECT JEUDI.AFFECTATION,SAMEDI.AFFECTATION FROM PROGRAMME_ENSEIGNEMENT AS JEUDI FULL JOIN PROGRAMME_ENSEIGNEMENT AS SAMEDI ON 
 JEUDI.JOUR='JEUDI' and SAMEDI.JOUR='SAMEDI' AND JEUDI.HEURE=SAMEDI.HEURE
GROUP BY JEUDI.HEURE,SAMEDI.AFFECTATION,JEUDI.AFFECTATION,SAMEDI.ID,JEUDI.ID,JEUDI.HEURE
 GROUP BY PROGRAMME_ENSEIGNEMENT.ID,PROGRAMME_ENSEIGNEMENT.AFFECTATION ORDER BY JEUDI.HEURE,SAMEDI.HEURE ASC



EXEC NOMBRE_HEURE 'LUNDI'

EXEC NOMBRE_HEURE 'MERCREDI'

CREATE PROC NOMBRE_HEURE
(@JOUR VARCHAR(10))
AS
BEGIN

DECLARE @END INT;
SELECT @END=PROGRAMME_JOURNE.NOMBRE_HEURE FROM PROGRAMME_JOURNE WHERE PROGRAMME_JOURNE.JOUR='jeudi'

DECLARE @i int = 1;
select @i;
WHILE(@i <= @END)
BEGIN
print @i;
SET @i = @i+1
END 

END

select 1

/*=========================================CONTRAINT DE REFERENCE==========================================================================*/
ALTER TABLE TITULARISATION_SALLE ADD CONSTRAINT FK_TITULARISATION_ANNE FOREIGN KEY (ANNE) REFERENCES ANNE_SCOLAIRE(ID)
ALTER TABLE DETAILS_ANNE_SCOLAIRE ADD CONSTRAINT FK_ANNE_DETAILS FOREIGN KEY (ID_ANNE) REFERENCES ANNE_SCOLAIRE(ID)
ALTER TABLE TITULARISATION_SALLE ADD CONSTRAINT FK_TITULARISATION_AGENT FOREIGN KEY (AGENT) REFERENCES AGENT(MATRICULE)
ALTER TABLE TITULARISATION_SALLE ADD CONSTRAINT FK_TITULARISATION_SALLE FOREIGN KEY (SALLE) REFERENCES DESIGNATION_SALLE(ID)
ALTER TABLE DETAILS_INSCRIPTION ADD CONSTRAINT FK_INSCRIPTION_ANNEE FOREIGN KEY (ANNE) REFERENCES ANNE_SCOLAIRE(ID)
ALTER TABLE DETAILS_INSCRIPTION ADD CONSTRAINT FK_DETAILS_INSCRIPTION FOREIGN KEY (ID_INSCRIPTION) REFERENCES INSCRIPTION_ELEVE(ID)
ALTER TABLE SALLE ADD CONSTRAINT FK_SALLE_SECTION FOREIGN KEY (SECTION) REFERENCES SECTION(ID)
ALTER TABLE PAIEMENT_FRAIS_INSCRIPTION ADD CONSTRAINT FK_PAIEMENT_FRAIS_INSCRIPTION FOREIGN KEY (ID_INSCRIPTION) REFERENCES INSCRIPTION_ELEVE(ID)
ALTER TABLE DETAILS_PAIEMENT_INSCRIPTION ADD CONSTRAINT FK_DETAILS_PAIEMENT_INSCRIPTION FOREIGN KEY (ID_PAIEMENT_FRAIS_INSCRIPTION) REFERENCES PAIEMENT_FRAIS_INSCRIPTION(ID)
ALTER TABLE FRAIS_INSCRIPTION ADD CONSTRAINT FK_FRAIS_INSCRIPTION_SALLE FOREIGN KEY (SALLE) REFERENCES SALLE(ID)
ALTER TABLE INSCRIPTION_ELEVE ADD CONSTRAINT FK_INSCRIPTION_ELEVE_SALLE FOREIGN KEY (SALLE) REFERENCES DESIGNATION_SALLE(ID)
ALTER TABLE DESIGNATION_SALLE ADD CONSTRAINT FK_DESIGNATION_SALLE FOREIGN KEY (ID_SALLE) REFERENCES SALLE(ID)
ALTER TABLE ELEVE ADD CONSTRAINT FK_ELEVE_INSCRIPTION FOREIGN KEY (MATRICULE) REFERENCES INSCRIPTION_ELEVE(MATRICULE)
ALTER TABLE ADDRESSE_ELEVE ADD CONSTRAINT FK_ADDRESSE_ELEVE FOREIGN KEY (MATRICULE) REFERENCES ELEVE(MATRICULE)
ALTER TABLE COORDONNES_ELEVE ADD CONSTRAINT FK_COORDONNES_ELEVE FOREIGN KEY (MATRICULE_ELEVE) REFERENCES ELEVE(MATRICULE)
ALTER TABLE TUTEUR ADD CONSTRAINT FK_TUTEUR_ELEVE FOREIGN KEY (MATRICULE_ELEVE) REFERENCES ELEVE(MATRICULE)
ALTER TABLE COORDONNES_TUTEUR ADD CONSTRAINT FK_COORDONNES_TUTEUR FOREIGN KEY (ID) REFERENCES TUTEUR(ID)
ALTER TABLE HORAIRE ADD CONSTRAINT FK_HORAIRE_ANNE FOREIGN KEY (ANNE) REFERENCES ANNE_SCOLAIRE(ID)
ALTER TABLE HORAIRE ADD CONSTRAINT FK_SALLE FOREIGN KEY (SALLE) REFERENCES SALLE(ID)
ALTER TABLE TRAVAIL ADD CONSTRAINT FK_TRAVAIL_COURS FOREIGN KEY (COURS) REFERENCES COURS(ID)
ALTER TABLE DETAILS_TRAVAIL ADD CONSTRAINT FK_DETAILS_TRAVAIL FOREIGN KEY (ID) REFERENCES TRAVAIL(ID)
ALTER TABLE COTATION ADD CONSTRAINT FK_DETAILS_TRAVAIL FOREIGN KEY (ID_TRAVAIL) REFERENCES TRAVAIL(ID)
ALTER TABLE COTATION ADD CONSTRAINT FK_COTATION_ELEVE FOREIGN KEY (MATRICULE_ELEVE) REFERENCES ELEVE(MATRICULE)
ALTER TABLE DETAILS_COTATION ADD CONSTRAINT FK_DETAILS_COTATION FOREIGN KEY (ID_COTATION) REFERENCES COTATION(ID)
ALTER TABLE COTATION ADD CONSTRAINT FK_COTATION_TRAVAIL FOREIGN KEY (ID_TRAVAIL) REFERENCES TRAVAIL(ID) ON DELETE CASCADE
ALTER TABLE BULLETIN ADD CONSTRAINT FK_BULLETIN_ELEVE FOREIGN KEY (MATRICULE_ELEVE) REFERENCES ELEVE(MATRICULE)
ALTER TABLE SALAIRE ADD CONSTRAINT FK_SALAAIRE_DEPARTEMENT FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT(ID)
ALTER TABLE AVANTAGE ADD CONSTRAINT FK_AVANTAGE_DEPARTEMENT FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT(ID)
ALTER TABLE INSCRIPTION_AGENT ADD CONSTRAINT FK_INSCRIPTION_AGENT_DEPARTEMENT FOREIGN KEY (DEPARTEMENT) REFERENCES DEPARTEMENT(ID)
ALTER TABLE DETAIL_INSCRIPTION_AGENT ADD CONSTRAINT FK_DETAIL_INSCRIPTION_AGENT FOREIGN KEY (ID_INSCRIPTION_AGENT) REFERENCES INSCRIPTION_AGENT(ID)
ALTER TABLE AGENT ADD CONSTRAINT FK_AGENT_INSCRIPTION FOREIGN KEY (MATRICULE) REFERENCES INSCRIPTION_AGENT(MATRICULE)
ALTER TABLE DETAIL_INSCRIPTION_AGENT ADD CONSTRAINT FK_DETAIL_INSCRIPTION_AGENT FOREIGN KEY (ID_INSCRIPTION_AGENT) REFERENCES INSCRIPTION_AGENT(ID)
ALTER TABLE SANCTION ADD CONSTRAINT FK_SANCTION_ELEVE FOREIGN KEY (MATRICULE_ELEVE) REFERENCES ELEVE(MATRICULE)
ALTER TABLE DETAILS_SANCTION ADD CONSTRAINT FK_DETAILS_SANCTION FOREIGN KEY (ID) REFERENCES SANCTION(ID)
ALTER TABLE DETAILS_TRAVAIL ADD CONSTRAINT FK_DETAILS_TRAVAIL_MOTIF FOREIGN KEY (MOTIF) REFERENCES MOTIF_INTERROGATION(ID)
ALTER TABLE QR_AGENT_PRESENCE ADD CONSTRAINT FK_AGENT_PRESENCE FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE)
ALTER TABLE DETAILS_QR_AGENT_PRESENCE ADD CONSTRAINT FK_DETAILS_QR_AGENT_PRESENCE FOREIGN KEY (ID_QR_AGENT_PRESENCE) REFERENCES QR_AGENT_PRESENCE(ID)
ALTER TABLE BULLETIN ADD CONSTRAINT FK_BULLETIN_ANNE FOREIGN KEY (ANNE) REFERENCES ANNE_SCOLAIRE(ID)
ALTER TABLE ADDRESSE_AGENT ADD CONSTRAINT FK_AGENT_ADDRESSE FOREIGN KEY (MATRICULE) REFERENCES AGENT(MATRICULE)
ALTER TABLE SALLE ADD CONSTRAINT FK_SALLE_NIVEAU FOREIGN KEY(NIVEAU_ETUDE) REFERENCES NIVEAU_ETUDE(NIVEAU)
ALTER TABLE HORAIRE ADD CONSTRAINT FK_COURS_HORAIRE FOREIGN KEY(COURS) REFERENCES COURS(ID)
ALTER TABLE HORAIRE ADD CONSTRAINT FK_ANNE_HORAIRE FOREIGN KEY(ANNE) REFERENCES ANNE_SCOLAIRE (ID)
ALTER TABLE AFFECTATION_COURS ADD CONSTRAINT FK_AFFECTATION_HORAIRE FOREIGN KEY(HORAIRE) REFERENCES HORAIRE (ID)
ALTER TABLE AFFECTATION_COURS ADD CONSTRAINT FK_AFFECTATION_DESIGNATION_SALLE FOREIGN KEY(DESIGNATION_SALLE) REFERENCES DESIGNATION_SALLE (ID)
ALTER TABLE AFFECTATION_COURS ADD CONSTRAINT FK_AFFECTATION_PROF FOREIGN KEY(PROF) REFERENCES AGENT (MATRICULE)
ALTER TABLE PROGRAMME_ENSEIGNEMENT ADD CONSTRAINT FK_PROGRAMME_ENSEIGNEMENT FOREIGN KEY(AFFECTATION) REFERENCES AFFECTATION_COURS (ID)
/*ALTER TABLE HORAIRE DROP CONSTRAINT FK_AGENT_HORAIRE FOREIGN KEY(PROF) REFERENCES AGENT(MATRICULE)
*//*=========================================PROCEDURE STOCOKER=========================================*/

CREATE PROC AJOUTER_DEPARTEMENT_SALAIRE
(@DESIGNATION VARCHAR(15),@MONTANT INT)
AS
BEGIN
	INSERT INTO DEPARTEMENT(DESIGNATION)VALUES(@DESIGNATION)
	INSERT INTO SALAIRE(ID_DEPARTEMENT,MONTANT)SELECT MAX(ID),@MONTANT FROM DEPARTEMENT
END


CREATE PROC MIN_DATE
as
BEGIN
declare @old int;
SELECT @old=YEAR(GETDATE())-18
select concat('01/01/','', @old,' 00:00')
END

CREATE PROC MAX_DATE
as
BEGIN
declare @old int;
SELECT @old=YEAR(GETDATE())-10
select concat('01/01/','', @old,' 00:00')
END

EXEC AJOUT_AGENT 'EXAUCE','MFX','VVMVC',NULL,NULL,'COMPTABILITE','087688','GOMA','KATINDO','BARAKA',9

alter PROC AJOUT_AGENT
(@NOM VARCHAR(25),@POSTNOM VARCHAR(25),@PRENOM VARCHAR(25),@DATE DATE,@IMAGE IMAGE ,
@DEPARTEMENTS VARCHAR(15),@TELEPHONE VARCHAR(10),@VILLE VARCHAR(15),@QUARTIER VARCHAR(15),@AVENU VARCHAR(15),@NUMERO INT)
AS
BEGIN

DECLARE @MATRICULE VARCHAR(10);
DECLARE @DEPARTEMENT_INT INT;
DECLARE @ID_INS INT;
SELECT @DEPARTEMENT_INT= ID FROM DEPARTEMENT WHERE DEPARTEMENT.DESIGNATION=@DEPARTEMENTS

SELECT @MATRICULE=CONCAT(YEAR(GETDATE()),'',SUBSTRING(@NOM,1,1),'',SUBSTRING(@POSTNOM,1,1),'',ISNULL(MAX(ID),0)) FROM INSCRIPTION_AGENT
INSERT INTO INSCRIPTION_AGENT (MATRICULE,DEPARTEMENT)VALUES(@MATRICULE,@DEPARTEMENT_INT)
SELECT @ID_INS=MAX(ID) FROM INSCRIPTION_AGENT
INSERT INTO AGENT(MATRICULE,NOM,POSTNOM,PRENOM,DATE,PHOTO)VALUES(@MATRICULE,@NOM,@POSTNOM,@PRENOM,@DATE,@IMAGE)
INSERT INTO ADDRESSE_AGENT (MATRICULE,TELEPHONE,VILLE,QUARTIER,AVENU,NUMERO) VALUES(@MATRICULE,@TELEPHONE,@VILLE,@QUARTIER,@AVENU,@NUMERO)
INSERT INTO DETAIL_INSCRIPTION_AGENT(ID_INSCRIPTION_AGENT)VALUES(@ID_INS)
END


alter PROC NOUVEAU_SALLE
(@NIVEAU INT,@SECTION VARCHAR(31),@DESIGNATION VARCHAR(1),@NOMBRE_PLACE INT,@NOM_PROF VARCHAR(45))
AS
BEGIN
	DECLARE @SECTION_ID INT;
	DECLARE @MATRICULE_PROF VARCHAR(10);
	DECLARE @SALLE_ID INT;
	SELECT @MATRICULE_PROF=AGENT.MATRICULE FROM AGENT WHERE CONCAT(NOM,' ',POSTNOM,' ',PRENOM)=@NOM_PROF
	SELECT @SECTION_ID=ID FROM SECTION WHERE SECTION.ABREVIATION=@SECTION

	 DECLARE @CHECK INT;

    SELECT @CHECK=COUNT(*) FROM SALLE WHERE SALLE.NIVEAU_ETUDE=@NIVEAU AND SALLE.SECTION=@SECTION_ID 
	IF(@CHECK<1)
	BEGIN

	INSERT INTO SALLE(SECTION,NIVEAU_ETUDE)VALUES(@SECTION_ID,@NIVEAU)
	INSERT INTO DESIGNATION_SALLE(ID_SALLE,LETTRE,NOMBRE_PLACE)SELECT ID,@DESIGNATION,@NOMBRE_PLACE FROM SALLE WHERE ID=(SELECT MAX(ID) FROM SALLE)
	SELECT @SALLE_ID=DESIGNATION_SALLE.ID FROM DESIGNATION_SALLE WHERE DESIGNATION_SALLE.ID=(SELECT MAX(ID) FROM DESIGNATION_SALLE)
	INSERT INTO TITULARISATION_SALLE(AGENT,SALLE,ANNE)SELECT @MATRICULE_PROF,@SALLE_ID, MAX(ID) FROM ANNE_SCOLAIRE

	END
	ELSE IF(@CHECK>=1)
	BEGIN
	declare @id_salle int;
	SELECT @id_salle=SALLE.ID FROM SALLE WHERE SALLE.NIVEAU_ETUDE=@NIVEAU and salle.SECTION=@SECTION_ID
	INSERT INTO DESIGNATION_SALLE(ID_SALLE,LETTRE,NOMBRE_PLACE)SELECT @id_salle,@DESIGNATION,@NOMBRE_PLACE 
	SELECT @SALLE_ID=DESIGNATION_SALLE.ID FROM DESIGNATION_SALLE WHERE DESIGNATION_SALLE.ID=(SELECT MAX(ID) FROM DESIGNATION_SALLE)
	INSERT INTO TITULARISATION_SALLE(AGENT,SALLE,ANNE)SELECT @MATRICULE_PROF,@SALLE_ID, MAX(ID) FROM ANNE_SCOLAIRE
	declare @designation_salle_id int;
	select @designation_salle_id = max(id) from DESIGNATION_SALLE

	INSERT INTO AFFECTATION_COURS(HORAIRE,DESIGNATION_SALLE,PROF)SELECT HORAIRE,@designation_salle_id,PROF FROM AFFECTATION_COURS INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=AFFECTATION_COURS.DESIGNATION_SALLE INNER JOIN SALLE
	ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE NIVEAU_ETUDE=1 AND SECTION.ABREVIATION='CO'
	AND DESIGNATION_SALLE.LETTRE='A'
	

	END

	DECLARE @i int = 1;
WHILE(@i <7)
BEGIN
INSERT INTO PROGRAMME_ENSEIGNEMENT(HEURE,designation_salle) select @i,max(id) from DESIGNATION_SALLE
SET @i = @i+1
END
	

END


EXEC ADMINISTRER_COURS_PROF '2co',50,'2021LT22','FRANCAIS'

SELECT * FROM HORAIRE
DELETE FROM HORAIRE


SELECT * FROM HORAIRE

exec ADMINISTRER_COURS_PROF 2,'ca','a',50,'2021LT22','MATH','A','NON'

 ALTER PROC DESIGNATION_COURS_AFFECTATION
  (@COURS VARCHAR(20) ,@NIVEAU_PARAMS INT,@ABREVIATION_PARAMS VARCHAR(10),@LETTRE VARCHAR(1))
  AS
  BEGIN
  SELECT AGENT.NOM,AGENT.POSTNOM,AGENT.POSTNOM,AGENT.PHOTO ,COURS.DESIGNATION,HORAIRE.PONDERATION ,SECTION.ABREVIATION,SALLE.NIVEAU_ETUDE,DESIGNATION_SALLE.LETTRE FROM AGENT INNER JOIN AFFECTATION_COURS ON AFFECTATION_COURS.PROF=AGENT.MATRICULE INNER JOIN HORAIRE
  ON HORAIRE.ID=AFFECTATION_COURS.HORAIRE INNER JOIN SALLE ON SALLE.ID=HORAIRE.SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION INNER JOIN DESIGNATION_SALLE
  ON DESIGNATION_SALLE.ID_SALLE=SALLE.ID AND DESIGNATION_SALLE.ID=AFFECTATION_COURS.DESIGNATION_SALLE INNER JOIN COURS ON COURS.ID=HORAIRE.COURS AND HORAIRE.SALLE=SALLE.ID
  WHERE NIVEAU_ETUDE=@NIVEAU_PARAMS AND ABREVIATION=@ABREVIATION_PARAMS AND LETTRE=@LETTRE AND COURS.DESIGNATION=@COURS
  END

select  PHOTO from AGENT INNER JOIN AFFECTATION_COURS ON AFFECTATION_COURS.PROF=AGENT.MATRICULE INNER JOIN HORAIRE  ON HORAIRE.ID=AFFECTATION_COURS.HORAIRE INNER JOIN SALLE ON SALLE.ID=HORAIRE.SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION INNER JOIN DESIGNATION_SALLE  ON DESIGNATION_SALLE.ID_SALLE=SALLE.ID AND DESIGNATION_SALLE.ID=AFFECTATION_COURS.DESIGNATION_SALLE INNER JOIN COURS ON COURS.ID=HORAIRE.COURS AND HORAIRE.SALLE=SALLE.ID  where  NIVEAU_ETUDE =1 AND CONCAT(' ',ABREVIATION) =' CO' AND LETTRE='B' AND COURS.DESIGNATION 'MATH '


ALTER PROC ADMINISTRER_COURS_PROF
(@niveau int,@section_par varchar(10),@SALLE VARCHAR(10),@PONDERATION INT,@PROF VARCHAR(10),@COURS VARCHAR(20),@LETTRE VARCHAR(1),@ens varchar(5),@nombre int)
AS
BEGIN
DECLARE @SALLE_INT INT,@ANNE INT,@CHECK INT,@COURS_ID INT,@salle_lettre int;
/*SELECT @SALLE_INT=  SALLE.ID FROM SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE CONCAT(SALLE.NIVEAU_ETUDE,'',SECTION.ABREVIATION)=@SALLE
*/
SELECT @ANNE=MAX(ANNE_SCOLAIRE.ID) FROM ANNE_SCOLAIRE

DECLARE @SECTION_ID INT;
SELECT @SECTION_ID=SECTION.ID FROM SECTION WHERE SECTION.ABREVIATION=@section_par

SELECT @SALLE_INT=SALLE.ID FROM SALLE WHERE SALLE.NIVEAU_ETUDE=@niveau AND SALLE.SECTION=@SECTION_ID

select @salle_lettre=ID_SALLE FROM DESIGNATION_SALLE INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN NIVEAU_ETUDE
ON NIVEAU_ETUDE.NIVEAU=SALLE.NIVEAU_ETUDE WHERE SALLE.NIVEAU_ETUDE=@niveau AND SALLE.SECTION=@SECTION_ID and DESIGNATION_SALLE.LETTRE=@LETTRE

SELECT @COURS_ID= ID FROM COURS WHERE COURS.DESIGNATION=@COURS
 SELECT @CHECK= COUNT(*) FROM HORAIRE WHERE SALLE=@SALLE_INT AND ANNE=@ANNE AND COURS=@COURS_ID
 DECLARE @ID_HORAIRE INT;
SELECT @ID_HORAIRE=AFFECTATION_COURS.HORAIRE FROM AFFECTATION_COURS INNER JOIN HORAIRE ON HORAIRE.ID=AFFECTATION_COURS.HORAIRE INNER JOIN SALLE ON SALLE.ID=HORAIRE.SALLE INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID_SALLE=SALLE.ID
 WHERE SALLE.NIVEAU_ETUDE=@niveau AND SALLE.SECTION=@SECTION_ID AND DESIGNATION_SALLE.LETTRE=@LETTRE AND HORAIRE.ANNE=@ANNE AND HORAIRE.COURS=@COURS_ID
	DECLARE @ID_DES INT;
SELECT @ID_DES= AFFECTATION_COURS.ID FROM AFFECTATION_COURS INNER JOIN HORAIRE ON HORAIRE.ID=AFFECTATION_COURS.HORAIRE INNER JOIN SALLE ON SALLE.ID=HORAIRE.SALLE INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID_SALLE=SALLE.ID
 AND DESIGNATION_SALLE.ID=AFFECTATION_COURS.DESIGNATION_SALLE WHERE SALLE.NIVEAU_ETUDE=@niveau AND SALLE.SECTION=@SECTION_ID AND DESIGNATION_SALLE.LETTRE=@LETTRE AND HORAIRE.ANNE=@ANNE AND HORAIRE.COURS=@COURS_ID
			
 IF(@CHECK>=1)
	BEGIN
	 
	 IF(@ENS='TOUT')
		BEGIN

		
			UPDATE HORAIRE SET PONDERATION=@PONDERATION, NOMBRE_JOURNALIER=@nombre WHERE COURS=@COURS_ID AND ANNE=@ANNE AND SALLE=@SALLE_INT
			UPDATE AFFECTATION_COURS SET PROF=@PROF WHERE AFFECTATION_COURS.HORAIRE=@ID_HORAIRE
		END
	ELSE IF(@ENS='NON')
		BEGIN
		    UPDATE AFFECTATION_COURS SET PROF=@PROF WHERE AFFECTATION_COURS.ID=@ID_DES
			UPDATE HORAIRE SET PONDERATION=@PONDERATION WHERE COURS=@COURS_ID AND ANNE=@ANNE AND SALLE=@SALLE_INT
		/*	
		UPDATE AFFECTATION_COURS SET PROF=@PROF WHERE AFFECTATION_COURS.DESIGNATION_SALLE=@salle_lettre AND AFFECTATION_COURS.ID=@ID_HORAIRE
		*/
		END
	  				
	END
 ELSE IF(@CHECK=0) 
  BEGIN
	INSERT INTO HORAIRE (SALLE,ANNE,PONDERATION,COURS,NOMBRE_JOURNALIER)select @SALLE_INT,@ANNE,@PONDERATION ,@COURS_ID,@nombre
	DECLARE @MAX_H INT;
	SELECT @MAX_H= MAX(ID) FROM HORAIRE
	INSERT INTO AFFECTATION_COURS (HORAIRE,DESIGNATION_SALLE,PROF)SELECT @MAX_H,DESIGNATION_SALLE.ID,@PROF FROM DESIGNATION_SALLE INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE WHERE SALLE.NIVEAU_ETUDE=@niveau AND SALLE.SECTION=@SECTION_ID
	
  END
END



ALTER PROC INSCRIPTION_ETUDIANT
(@NOM VARCHAR(15),@POSTNOM VARCHAR(15),@PRENOM VARCHAR(15),@PHOTO IMAGE,@NIVEAU INT,@SECTION VARCHAR(5),@ABREVIATION VARCHAR(1),
@EMAIL VARCHAR(35),@CELLULAIRE VARCHAR(14),@PAYS VARCHAR(15),@PROVINCE VARCHAR(15),@VILLE VARCHAR(15),@QUARTIER VARCHAR(15),@AVENU VARCHAR(15),@NUMERO INT,@NOM_T VARCHAR(15),
@POSTNOM_T VARCHAR(15),@PRENOM_T VARCHAR(15),@EMAIL_T VARCHAR(35),@CELLULAIRE_T VARCHAR(14))
AS
BEGIN
	DECLARE @ID_DESIGNATION_SALLE INT;
	DECLARE @MATRICULE VARCHAR(15);
	DECLARE @ID_INS INT;
	DECLARE @ID_TUTILAIRE INT;

	SELECT @ID_TUTILAIRE=  ID FROM TUTEUR WHERE TUTEUR.MATRICULE_ELEVE=@MATRICULE
	SELECT MAX(ID) FROM INSCRIPTION_ELEVE
	SELECT @MATRICULE=CONCAT(YEAR(getdate()),'',SUBSTRING(@NOM,1,1),'',SUBSTRING(@POSTNOM,1,1),'',(SELECT FORMAT(ISNULL(MAX(ID),0)+1,'0000') FROM INSCRIPTION_ELEVE))
	SELECT @ID_DESIGNATION_SALLE=DESIGNATION_SALLE.ID FROM DESIGNATION_SALLE INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION  ON SECTION.ID=SALLE.SECTION WHERE SALLE.NIVEAU_ETUDE=@NIVEAU AND SECTION.ABREVIATION=@SECTION AND DESIGNATION_SALLE.LETTRE=@ABREVIATION
	INSERT INTO INSCRIPTION_ELEVE(MATRICULE,SALLE)VALUES(@MATRICULE,@ID_DESIGNATION_SALLE)
	SELECT @ID_INS=MAX(ID) FROM INSCRIPTION_ELEVE
	INSERT INTO DETAILS_INSCRIPTION(ID_INSCRIPTION,ANNE)VALUES(@ID_INS,(SELECT MAX(ID) FROM ANNE_SCOLAIRE))
	INSERT INTO ELEVE(MATRICULE,NOM,POSTNOM,PRENOM,DATE,PHOTO)VALUES(@MATRICULE,@NOM,@POSTNOM,@PRENOM,'2000-11-11',@PHOTO)
	INSERT INTO ADDRESSE_ELEVE(MATRICULE,PAYS,PROVINCE,VILLE,QUARTIER,NUMERO)VALUES(@MATRICULE,@PAYS,@PROVINCE,@VILLE,@QUARTIER,@NUMERO)
	INSERT INTO COORDONNES_ELEVE(MATRICULE_ELEVE,EMAIL,CELULAIRE)VALUES(@MATRICULE,@EMAIL,@CELLULAIRE)
	INSERT INTO TUTEUR(MATRICULE_ELEVE,NOM,POSTNOM,PRENOM)VALUES(@MATRICULE,@NOM_T,@POSTNOM_T,@PRENOM_T)
	SELECT @ID_TUTILAIRE= ID FROM TUTEUR WHERE TUTEUR.MATRICULE_ELEVE=@MATRICULE
	INSERT INTO COORDONNES_TUTEUR(ID,EMAIL,CELULAIRE)VALUES(@ID_TUTILAIRE,@EMAIL_T,@CELLULAIRE_T)
END


SELECT * FROM INSCRIPTION_ELEVE
SELECT * FROM DETAILS_INSCRIPTION
SELECT * FROM ELEVE
SELECT * FROM ADDRESSE_ELEVE
SELECT * FROM COORDONNES_ELEVE
SELECT * FROM TUTEUR
SELECT * FROM COORDONNES_TUTEUR


DELETE FROM DESIGNATION_SALLE
SELECT * FROM ADDRESSE_ELEVE
DELETE FROM SALLE
DELETE FROM HORAIRE
DELETE FROM INSCRIPTION_ELEVE
DELETE FROM DETAILS_INSCRIPTION
DELETE FROM ELEVE
DELETE FROM ADDRESSE_ELEVE
DELETE FROM COORDONNES_ELEVE
DELETE FROM TUTEUR
DELETE FROM COORDONNES_TUTEUR
DELETE FROM DESIGNATION_SALLE
DELETE FROM AFFECTATION_COURS
DELETE FROM TITULARISATION_SALLE
DELETE FROM PROGRAMME_ENSEIGNEMENT


SELECT * FROM PROGRAMME_ENSEIGNEMENT

DECLARE @JOUR VARCHAR(10);
SELECT @JOUR='LUNDI'

SELECT @JOUR FROM PROGRAMME_ENSEIGNEMENT

EXEC KUYA

SELECT HORAIRE.SALLE,SALLE.NIVEAU_ETUDE,SALLE.SECTION FROM HORAIRE INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID_SALLE
=HORAIRE.ID INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE

delete from HORAIRE
DELETE FROM AFFECTATION_COURS
select * from HORAIRE
SELECT * FROM AFFECTATION_COURS

SELECT LETTRE FROM SALLE_DE_CLASS WHERE NIVEAU_ETUDE=2 AND ABREVIATION='CA' 

SELECT * FROM SALLE
SELECT * FROM DESIGNATION_SALLE
SELECT * FROM TITULARISATION_SALLE

SELECT * FROM HORAIRE

delete from AFFECTATION_COURS
DELETE FROM HORAIRE

SELECT COUNT(*)
 FROM SALLE INNER JOIN DESIGNATION_SALLE on SALLE.ID=DESIGNATION_SALLE.ID_SALLE
INNER JOIN SECTION ON SALLE.SECTION=SECTION.ID where LETTRE='A' AND NIVEAU_ETUDE=1 AND SECTION.ABREVIATION='CA'

SELECT COUNT(*) FROM SALLE INNER JOIN DESIGNATION_SALLE on SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SALLE.SECTION=SECTION.ID where LETTRE='a' AND SECTION.ABREVIATION='CO' AND NIVEAU_ETUDE=1


SELECT SALLE.NIVEAU_ETUDE,SECTION.ABREVIATION,DESIGNATION_SALLE.LETTRE,DESIGNATION_SALLE.NOMBRE_PLACE FROM SALLE INNER JOIN DESIGNATION_SALLE on SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SALLE.SECTION=SECTION.ID where LETTRE='a'

SELECT * FROM AGENT
SELECT * FROM TITULARISATION_SALLE

select * from agent where agent.NOM =(select TITULARISATION_SALLE.AGENT from TITULARISATION_SALLE)

SELECT CONCAT(NOM,' ',POSTNOM ,' ',PRENOM) FROM AGENT LEFT JOIN TITULARISATION_SALLE ON TITULARISATION_SALLE.AGENT
=AGENT.MATRICULE AND TITULARISATION_SALLE.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE) WHERE  ISNULL(TITULARISATION_SALLE.SALLE,0)=0

delete from agent 
delete from INSCRIPTION_AGENT
delete from ADDRESSE_AGENT
delete from DETAIL_INSCRIPTION_AGENT
EXEC AJOUT_AGENT 'EXAUCE','MFX','VVMVC',NULL,NULL,'COMPTABILITE','087688','GOMA','KATINDO','BARAKA',9

DELETE from SALLE
DELETE FROM DESIGNATION_SALLE
DELETE FROM TITULARISATION_SALLE
SELECT * from INSCRIPTION_AGENT
select * from DETAIL_INSCRIPTION_AGENT
select * from ADDRESSE_AGENT
SELECT DETAIL_INSCRIPTION_AGENT.DATE
select COUNT(*) from DEPARTEMENT
SELECT INSCRIPTION_AGENT.MATRICULE,AGENT.NOM,AGENT.POSTNOM,AGENT.PRENOM,DEPARTEMENT.DESIGNATION,DATEDIFF(YEAR,DETAIL_INSCRIPTION_AGENT.DATE,GETDATE()) AS ANCIENNETE FROM INSCRIPTION_AGENT INNER JOIN AGENT ON INSCRIPTION_AGENT.MATRICULE=AGENT.MATRICULE INNER JOIN DEPARTEMENT ON DEPARTEMENT.ID=INSCRIPTION_AGENT.DEPARTEMENT INNER JOIN DETAIL_INSCRIPTION_AGENT ON DETAIL_INSCRIPTION_AGENT.ID_INSCRIPTION_AGENT=INSCRIPTION_AGENT.ID
SELECT * FROM DEPARTEMENT
SELECT * FROM SALAIRE


================================

select DESIGNATION from DEPARTEMENT
SELECT DATEDIFF(YEAR,'2020-01-01','2020-02-02')

CREATE PROC MIN_DATE
BEGIN
declare @old int;
SELECT @old=YEAR(GETDATE())-18
select concat('01/01','', @old)
END

SELECT SALLE.NIVEAU_ETUDE,SECTION.DESIGNATION,DESIGNATION_SALLE.LETTRE,DESIGNATION_SALLE.NOMBRE_PLACE,CONCAT(
AGENT.NOM,' ',AGENT.POSTNOM,' ',PRENOM) AS TITULAIRE
 FROM SALLE INNER JOIN DESIGNATION_SALLE on SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON
  SALLE.SECTION=SECTION.ID INNER JOIN TITULARISATION_SALLE ON TITULARISATION_SALLE.SALLE=DESIGNATION_SALLE.ID INNER JOIN
  AGENT ON AGENT.MATRICULE=TITULARISATION_SALLE.AGENT


  ==============================================CREATE VIEW==============================

  ALTER VIEW COURS_SALLE
  AS(
  
 SELECT AFFECTATION_COURS.ID,COURS.DESIGNATION,HORAIRE.PONDERATION,AGENT.MATRICULE ,AGENT.NOM,AGENT.POSTNOM,AGENT.PRENOM,
 SALLE.NIVEAU_ETUDE,SECTION.ABREVIATION,DESIGNATION_SALLE.LETTRE,HORAIRE.NOMBRE_JOURNALIER,DESIGNATION_SALLE.ID AS ID_DESIGNATION_SALLE FROM AFFECTATION_COURS INNER JOIN DESIGNATION_SALLE
 ON DESIGNATION_SALLE.ID=AFFECTATION_COURS.DESIGNATION_SALLE INNER JOIN AGENT ON AGENT.MATRICULE=AFFECTATION_COURS.PROF INNER JOIN
  HORAIRE ON HORAIRE.ID=AFFECTATION_COURS.HORAIRE INNER JOIN COURS ON COURS.ID=HORAIRE.COURS INNER JOIN SALLE ON SALLE.ID=HORAIRE.SALLE
  INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE HORAIRE.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE)

  )


  SELECT COUNT(COURS_SALLE.DESIGNATION) FROM COURS_SALLE WHERE NIVEAU_ETUDE=1 AND ABREVIATION='CA' AND LETTRE='A'

  DROP PROC 
  DELETE FROM PROGRAMME_ENSEIGNEMENT
  EXEC PROGRAMMER_COURS_HORAIRE 1,'CA','A','GEOGRAPHIE','MARDI',1
 SELECT * FROM PROGRAMME_ENSEIGNEMENT

  alter PROC PROGRAMMER_COURS_HORAIRE(@NIVEAU INT,@ABREVIATION VARCHAR(5),@LETTRE VARCHAR(1),@COURS VARCHAR(15),@JOUR VARCHAR(10),@HEURE INT)
  AS
  BEGIN
	DECLARE @ID_PROGRAMME INT; 
	SELECT @ID_PROGRAMME=ID FROM COURS_SALLE WHERE NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE AND DESIGNATION=@COURS
	DECLARE @ID_SALLE INT; 
	SELECT @ID_SALLE=ID_DESIGNATION_SALLE FROM COURS_SALLE WHERE NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE AND DESIGNATION=@COURS
	if(@JOUR='LUNDI')
	begin
		
	UPDATE PROGRAMME_ENSEIGNEMENT SET LUNDI=@ID_PROGRAMME  WHERE HEURE=@HEURE AND designation_salle=@ID_SALLE
	end
	ELSE IF(@JOUR='MARDI')
	begin
		
	UPDATE PROGRAMME_ENSEIGNEMENT SET MARDI=@ID_PROGRAMME  WHERE HEURE=@HEURE AND designation_salle=@ID_SALLE
	end
	ELSE IF(@JOUR='MERCREDI')
	begin
		
	UPDATE PROGRAMME_ENSEIGNEMENT SET MERCREDI=@ID_PROGRAMME  WHERE HEURE=@HEURE AND designation_salle=@ID_SALLE
	end
	ELSE IF(@JOUR='JEUDI')
	begin
		
	UPDATE PROGRAMME_ENSEIGNEMENT SET JEUDI=@ID_PROGRAMME  WHERE HEURE=@HEURE AND designation_salle=@ID_SALLE
	end
	ELSE IF(@JOUR='VENDREDI')
	begin
		
	UPDATE PROGRAMME_ENSEIGNEMENT SET VENDREDI=@ID_PROGRAMME  WHERE HEURE=@HEURE AND designation_salle=@ID_SALLE
	end
	ELSE IF(@JOUR='SAMEDI')
	begin
		
	UPDATE PROGRAMME_ENSEIGNEMENT SET SAMEDI=@ID_PROGRAMME  WHERE HEURE=@HEURE AND designation_salle=@ID_SALLE
	end
  END


  ALTER VIEW LUNDI
  AS(
  SELECT SECTION.ABREVIATION,SALLE.NIVEAU_ETUDE,DESIGNATION_SALLE.LETTRE,C_LUNDI.DESIGNATION,P_LUNDI.designation_salle,P_LUNDI.HEURE,A_LUNDI.PROF  FROM PROGRAMME_ENSEIGNEMENT AS P_LUNDI LEFT JOIN AFFECTATION_COURS AS A_LUNDI ON P_LUNDI.LUNDI=A_LUNDI.ID LEFT JOIN 
  HORAIRE AS H_LUNDI ON A_LUNDI.HORAIRE=H_LUNDI.ID  LEFT JOIN COURS AS C_LUNDI ON C_LUNDI.ID=H_LUNDI.COURS LEFT JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=A_LUNDI.DESIGNATION_SALLE LEFT JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE LEFT JOIN SECTION ON SECTION.ID=SALLE.ID
  )
  ALTER VIEW PROGRAMME_GENERAL
  AS
  (
  SELECT SALLE.NIVEAU_ETUDE,SECTION.ABREVIATION,DESIGNATION_SALLE.LETTRE ,LUNDI.designation_salle,LUNDI.HEURE  ,LUNDI.DESIGNATION AS LUNDI,CONCAT(MARDI.DESIGNATION,':', MARDI.PROF) AS MARDI ,MERCREDI.DESIGNATION AS MERCREDI,JEUDI.DESIGNATION AS JEUDI,VENDREDI.DESIGNATION AS VENDREDI,SAMEDI.DESIGNATION AS SAMEDI FROM LUNDI INNER JOIN MARDI ON LUNDI.HEURE=MARDI.HEURE AND LUNDI.designation_salle=MARDI.designation_salle
  INNER JOIN MERCREDI ON MERCREDI.designation_salle=LUNDI.designation_salle and MERCREDI.HEURE=MARDI.HEURE 
  INNER JOIN JEUDI ON JEUDI.designation_salle=LUNDI.designation_salle and JEUDI.HEURE=MARDI.HEURE
  INNER JOIN VENDREDI ON VENDREDI.designation_salle=LUNDI.designation_salle and VENDREDI.HEURE=MARDI.HEURE
  INNER JOIN SAMEDI ON SAMEDI.designation_salle=LUNDI.designation_salle and SAMEDI.HEURE=MARDI.HEURE
  INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=LUNDI.designation_salle INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE
  INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION
  )

  SELECT LUNDI,MARDI,MERCREDI,JEUDI,VENDREDI,SAMEDI,NIVEAU_ETUDE,ABREVIATION,LETTRE FROM PROGRAMME_GENERAL

  ALTER VIEW MARDI
  AS(
 SELECT C_MARDI.DESIGNATION,P_MARDI.designation_salle,P_MARDI.HEURE,A_MARDI.PROF FROM PROGRAMME_ENSEIGNEMENT AS P_MARDI LEFT JOIN AFFECTATION_COURS AS A_MARDI ON P_MARDI.MARDI=A_MARDI.ID LEFT JOIN 
  HORAIRE AS H_MARDI ON A_MARDI.HORAIRE=H_MARDI.ID  LEFT JOIN COURS AS C_MARDI ON C_MARDI.ID=H_MARDI.COURS
   )

   SELECT * FROM PROGRAMME_GENERAL

   CREATE PROC DEJA_PROGRAMMER_COURS
   (@COURS VARCHAR(10),@NIVEAU INT,@ABREVIATION VARCHAR(5),@LETTRE VARCHAR(1))
   AS
   BEGIN
   SELECT COUNT(LUNDI)
   +(SELECT COUNT(MARDI) FROM PROGRAMME_GENERAL WHERE MARDI=@COURS AND NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE)
   +(SELECT COUNT(MERCREDI) FROM PROGRAMME_GENERAL WHERE MERCREDI=@COURS AND NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE)
   +(SELECT COUNT(JEUDI) FROM PROGRAMME_GENERAL WHERE JEUDI=@COURS AND NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE)
   +(SELECT COUNT(VENDREDI) FROM PROGRAMME_GENERAL WHERE VENDREDI=@COURS AND NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE)
   +(SELECT COUNT(SAMEDI) FROM PROGRAMME_GENERAL WHERE SAMEDI=@COURS AND NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE)
    FROM PROGRAMME_GENERAL WHERE LUNDI=@COURS AND NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE
	END

	EXEC DEJA_PROGRAMMER_COURS




   ALTER VIEW MERCREDI
  AS(
 SELECT C_MERCREDI.DESIGNATION,P_MERCREDI.designation_salle,P_MERCREDI.HEURE,A_MERCREDI.PROF FROM PROGRAMME_ENSEIGNEMENT AS P_MERCREDI LEFT JOIN AFFECTATION_COURS AS A_MERCREDI ON P_MERCREDI.MERCREDI=A_MERCREDI.ID LEFT JOIN 
  HORAIRE AS H_MERCREDI ON A_MERCREDI.HORAIRE=H_MERCREDI.ID  LEFT JOIN COURS AS C_MERCREDI ON C_MERCREDI.ID=H_MERCREDI.COURS
   )

  ALTER VIEW JEUDI
  AS(
 SELECT C_MERCREDI.DESIGNATION,P_MERCREDI.designation_salle,P_MERCREDI.HEURE,A_MERCREDI.PROF FROM PROGRAMME_ENSEIGNEMENT AS P_MERCREDI LEFT JOIN AFFECTATION_COURS AS A_MERCREDI ON P_MERCREDI.JEUDI=A_MERCREDI.ID LEFT JOIN 
  HORAIRE AS H_MERCREDI ON A_MERCREDI.HORAIRE=H_MERCREDI.ID  LEFT JOIN COURS AS C_MERCREDI ON C_MERCREDI.ID=H_MERCREDI.COURS
   )

    ALTER VIEW VENDREDI
  AS(
 SELECT C_MERCREDI.DESIGNATION,P_MERCREDI.designation_salle,P_MERCREDI.HEURE,A_MERCREDI.PROF FROM PROGRAMME_ENSEIGNEMENT AS P_MERCREDI LEFT JOIN AFFECTATION_COURS AS A_MERCREDI ON P_MERCREDI.VENDREDI=A_MERCREDI.ID LEFT JOIN 
  HORAIRE AS H_MERCREDI ON A_MERCREDI.HORAIRE=H_MERCREDI.ID  LEFT JOIN COURS AS C_MERCREDI ON C_MERCREDI.ID=H_MERCREDI.COURS
   )

     ALTER VIEW SAMEDI
  AS(
 SELECT C_MERCREDI.DESIGNATION,P_MERCREDI.designation_salle,P_MERCREDI.HEURE,A_MERCREDI.PROF FROM PROGRAMME_ENSEIGNEMENT AS P_MERCREDI LEFT JOIN AFFECTATION_COURS AS A_MERCREDI ON P_MERCREDI.SAMEDI=A_MERCREDI.ID LEFT JOIN 
  HORAIRE AS H_MERCREDI ON A_MERCREDI.HORAIRE=H_MERCREDI.ID  LEFT JOIN COURS AS C_MERCREDI ON C_MERCREDI.ID=H_MERCREDI.COURS
   )
   SELECT * FROM PROGRAMME_ENSEIGNEMENT

  SELECT * FROM LUNDI
  SELECT * FROM MARDI

  EXEC SELECTIONNER_RESSEMBLANCE_HORAIRE 'JEUDI','2021MM0',3


  CREATE PROC SELECTIONNER_RESSEMBLANCE_HORAIRE
  (@JOUR VARCHAR(10),@PROF VARCHAR(10),@HEURE INT)
  AS
  BEGIN

		if(@JOUR='LUNDI')
		BEGIN
						SELECT LUNDI.DESIGNATION,CONCAT(SALLE.NIVEAU_ETUDE,'eme',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE)  FROM LUNDI INNER JOIN DESIGNATION_SALLE ON
			 DESIGNATION_SALLE.ID=designation_salle
			 INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE HEURE=@HEURE AND LUNDI.PROF=@PROF
		
		END
		if(@JOUR='MARDI')
		BEGIN
						SELECT MARDI.DESIGNATION,CONCAT(SALLE.NIVEAU_ETUDE,'eme',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE) FROM MARDI INNER JOIN DESIGNATION_SALLE ON
			 DESIGNATION_SALLE.ID=designation_salle
			 INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE HEURE=@HEURE AND MARDI.PROF=@PROF
		
		END
		if(@JOUR='MERCREDI')
		BEGIN
					SELECT MERCREDI.DESIGNATION,CONCAT(SALLE.NIVEAU_ETUDE,'eme',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE)  FROM MERCREDI INNER JOIN DESIGNATION_SALLE ON
			 DESIGNATION_SALLE.ID=designation_salle
			 INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE HEURE=@HEURE AND MERCREDI.PROF=@PROF
		
		END
		if(@JOUR='JEUDI')
		BEGIN
		
				SELECT JEUDI.DESIGNATION,CONCAT(SALLE.NIVEAU_ETUDE,'eme',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE)  FROM JEUDI INNER JOIN DESIGNATION_SALLE ON
			 DESIGNATION_SALLE.ID=designation_salle
			 INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE HEURE=@HEURE AND JEUDI.PROF=@PROF
		END
		if(@JOUR='VENDREDI')
		BEGIN
				SELECT VENDREDI.DESIGNATION,CONCAT(SALLE.NIVEAU_ETUDE,'eme',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE)  FROM VENDREDI INNER JOIN DESIGNATION_SALLE ON
			 DESIGNATION_SALLE.ID=designation_salle
			 INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE HEURE=@HEURE AND VENDREDI.PROF=@PROF
		END
		if(@JOUR='SAMEDI')
		BEGIN
			SELECT SAMEDI.DESIGNATION,CONCAT(SALLE.NIVEAU_ETUDE,'eme',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE)   FROM SAMEDI INNER JOIN DESIGNATION_SALLE ON
			 DESIGNATION_SALLE.ID=designation_salle
			 INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE HEURE=@HEURE AND SAMEDI.PROF=@PROF
		END


  END



  SELECT * FROM COURS_SALLE WHERE DESIGNATION='ECM' AND NIVEAU_ETUDE=1 AND ABREVIATION='CA' AND LETTRE='A'
  SELECT DESIGNATION,PONDERATION,MATRICULE FROM COURS_SALLE WHERE NIVEAU_ETUDE=1 AND ABREVIATION='CO' AND LETTRE='A'

  ALTER VIEW SALLE_DE_CLASS
  AS 
 (
	
SELECT SALLE.NIVEAU_ETUDE,SECTION.DESIGNATION, SECTION.ABREVIATION,DESIGNATION_SALLE.LETTRE,DESIGNATION_SALLE.NOMBRE_PLACE,COUNT(INSCRIPTION_ELEVE.MATRICULE) AS NOMBRE_INSCRIT,
CONCAT(AGENT.NOM,' ',AGENT.POSTNOM,' ',AGENT.PRENOM) AS TITULAIRE FROM SALLE INNER JOIN DESIGNATION_SALLE on SALLE.ID=DESIGNATION_SALLE.ID_SALLE 
INNER JOIN SECTION ON  SALLE.SECTION=SECTION.ID INNER JOIN TITULARISATION_SALLE ON TITULARISATION_SALLE.SALLE=DESIGNATION_SALLE.ID INNER JOIN  
AGENT ON AGENT.MATRICULE=TITULARISATION_SALLE.AGENT LEFT JOIN INSCRIPTION_ELEVE ON INSCRIPTION_ELEVE.SALLE=DESIGNATION_SALLE.ID_SALLE LEFT JOIN DETAILS_INSCRIPTION ON DETAILS_INSCRIPTION.ID_INSCRIPTION=INSCRIPTION_ELEVE.ID
 AND DETAILS_INSCRIPTION.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE) WHERE TITULARISATION_SALLE.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE) GROUP BY 
 SALLE.NIVEAU_ETUDE,SECTION.DESIGNATION, SECTION.ABREVIATION ,ABREVIATION,DESIGNATION_SALLE.LETTRE,DESIGNATION_SALLE.NOMBRE_PLACE,NOM,POSTNOM,PRENOM

  )

  SELECT * FROM SALLE_DE_CLASS

  ALTER VIEW LISTE_INSCRIT_JOURNALIER
  AS
  (
  SELECT   INSCRIPTION_ELEVE.MATRICULE,ELEVE.NOM,ELEVE.POSTNOM,ELEVE.PRENOM, CONCAT(SALLE.NIVEAU_ETUDE,'émè',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE) AS CLASSE,
  SALLE.NIVEAU_ETUDE,SECTION.ABREVIATION,DESIGNATION_SALLE.LETTRE,ADDRESSE_ELEVE.NUMERO,ADDRESSE_ELEVE.PAYS,ADDRESSE_ELEVE.PROVINCE,ADDRESSE_ELEVE.QUARTIER,ADDRESSE_ELEVE.VILLE,TUTEUR.NOM AS NOM_TUTEUR,TUTEUR.POSTNOM AS TUTEUR_POSTNOM,TUTEUR.PRENOM AS TUTEUR_PRENOM,COORDONNES_TUTEUR.CELULAIRE,COORDONNES_TUTEUR.EMAIL,DETAILS_INSCRIPTION.DATE,DETAILS_INSCRIPTION.HEURE,COORDONNES_ELEVE.EMAIL AS EMAIL_ELEVE,COORDONNES_ELEVE.CELULAIRE AS CELLULAIRE_ELEVE FROM COORDONNES_ELEVE INNER JOIN INSCRIPTION_ELEVE ON INSCRIPTION_ELEVE.MATRICULE=COORDONNES_ELEVE.MATRICULE_ELEVE INNER JOIN ELEVE ON ELEVE.MATRICULE=INSCRIPTION_ELEVE.MATRICULE
INNER JOIN DETAILS_INSCRIPTION ON DETAILS_INSCRIPTION.ID_INSCRIPTION=INSCRIPTION_ELEVE.ID inner JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=INSCRIPTION_ELEVE.SALLE
INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION INNER JOIN ADDRESSE_ELEVE ON ADDRESSE_ELEVE.MATRICULE=ELEVE.MATRICULE INNER JOIN TUTEUR ON TUTEUR.MATRICULE_ELEVE=ELEVE.MATRICULE INNER JOIN COORDONNES_TUTEUR ON COORDONNES_TUTEUR.ID=TUTEUR.ID  WHERE DETAILS_INSCRIPTION.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE)

  )

  SELECT MATRICULE,NOM,POSTNOM,PRENOM,CLASSE,HEURE FROM LISTE_INSCRIT_JOURNALIER WHERE DATE=FORMAT(GETDATE(),'yyyy-MM-dd')


  SELECT LETTRE,NOMBRE_PLACE,TITULAIRE FROM SALLE_DE_CLASS WHERE NIVEAU_ETUDE=1 AND ABREVIATION='CO'


  SELECT * FROM LISTE_INSCRIT_JOURNALIER
  EXEC SITUATION_TITULARISATIO 1,'CA','A'


  SELECT MATRICULE,NOM,POSTNOM,PRENOM,CLASSE FROM LISTE_INSCRIT_JOURNALIER WHERE NIVEAU_ETUDE=1 AND ABREVIATION='CA' AND LETTRE='A'
SELECT * from LISTE_INSCRIT_JOURNALIER WHERE NOM='MUTINDIAPALA' AND POSTNOM='EXAUCE' AND PRENOM='EXAUCE'
===========================================================================================
  SELECT * FROM AGENT
  SELECT * from INSCRIPTION_AGENT
  SELECT * from DEPARTEMENT
  select * from DETAILS_INSCRIPTION
  SELECT SALLE_DE_CLASS.ABREVIATION, LETTRE,NOMBRE_PLACE,TITULAIRE FROM SALLE_DE_CLASS WHERE NIVEAU_ETUDE=2 AND ABREVIATION='CA'
  SELECT LETTRE,NOMBRE_PLACE,TITULAIRE FROM SALLE_DE_CLASS WHERE NIVEAU_ETUDE=2 AND ABREVIATION='CA'

  SELECT TOP 15 INSCRIPTION_AGENT.MATRICULE,AGENT.NOM,AGENT.POSTNOM,AGENT.PRENOM,DEPARTEMENT.DESIGNATION FROM INSCRIPTION_AGENT   INNER JOIN AGENT ON AGENT.MATRICULE=INSCRIPTION_AGENT.MATRICULE INNER JOIN DEPARTEMENT ON DEPARTEMENT.ID=INSCRIPTION_AGENT.DEPARTEMENT WHERE CONCAT(NOM,' ',POSTNOM,' ',PRENOM)
  SELECT DETAIL_INSCRIPTION_AGENT.DATE-GETDATE() FROM DETAIL_INSCRIPTION_AGENT


  SELECT * FROM TITULARISATION_SALLE

  SELECT ISNULL(CONCAT(NIVEAU_ETUDE.NIVEAU,'eme',SECTION.ABREVIATION,'/',DESIGNATION_SALLE.LETTRE)
  FROM NIVEAU_ETUDE INNER JOIN SALLE ON NIVEAU_ETUDE.NIVEAU=SALLE.NIVEAU_ETUDE INNER JOIN SECTION ON
   SECTION.ID=SALLE.SECTION INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID_SALLE=SALLE.ID INNER JOIN 
   TITULARISATION_SALLE ON TITULARISATION_SALLE.SALLE=DESIGNATION_SALLE.ID WHERE TITULARISATION_SALLE.AGENT=
   SELECT COURS.DESIGNATION FROM COURS
   lundi




   ALTER PROC ADMINISTRER_COURS_PROF
(@niveau int,@section_par varchar(10),@SALLE VARCHAR(10),@PONDERATION INT,@PROF VARCHAR(10),@COURS VARCHAR(20),@LETTRE VARCHAR(1),@ens varchar(5))
AS
BEGIN
DECLARE @SALLE_INT INT,@ANNE INT,@CHECK INT,@COURS_ID INT,@salle_lettre int;
/*SELECT @SALLE_INT=  SALLE.ID FROM SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE CONCAT(SALLE.NIVEAU_ETUDE,'',SECTION.ABREVIATION)=@SALLE
*/
SELECT @ANNE=MAX(ANNE_SCOLAIRE.ID) FROM ANNE_SCOLAIRE

DECLARE @SECTION_ID INT;
SELECT @SECTION_ID=SECTION.ID FROM SECTION WHERE SECTION.ABREVIATION=@section_par

SELECT @SALLE_INT= ID_SALLE FROM DESIGNATION_SALLE INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN NIVEAU_ETUDE
ON NIVEAU_ETUDE.NIVEAU=SALLE.NIVEAU_ETUDE WHERE SALLE.NIVEAU_ETUDE=@niveau AND SALLE.SECTION=@SECTION_ID


SELECT @COURS_ID= ID FROM COURS WHERE COURS.DESIGNATION=@COURS
 SELECT @CHECK= COUNT(*) FROM HORAIRE WHERE SALLE=@SALLE_INT AND ANNE=@ANNE AND COURS=@COURS_ID
 
	INSERT INTO HORAIRE (SALLE,ANNE,PONDERATION,PROF,COURS)select @SALLE_INT,@ANNE,@PONDERATION ,@PROF,@COURS_ID
	
 SELECT COURS.DESIGNATION,HORAIRE.PONDERATION AS '1P',HORAIRE.PONDERATION AS '2P',HORAIRE.PONDERATION*2 AS 'EXAM',HORAIRE.PONDERATION*4 AS
  'SEMESTRE' FROM COURS INNER JOIN HORAIRE ON HORAIRE.COURS=COURS.ID INNER JOIN SALLE ON SALLE.ID=HORAIRE.SALLE INNER 
  JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE SECTION.ABREVIATION='CA' AND SALLE.NIVEAU_ETUDE=2
  UNION
SELECT 'TOTAL' AS 'COURS.DESIGNATION',SUM(HORAIRE.PONDERATION) AS '1P',SUM(HORAIRE.PONDERATION) AS '2P',SUM(HORAIRE.PONDERATION*2) AS 'EXAM',SUM(HORAIRE.PONDERATION*4) AS
  'SEMESTRE' FROM COURS INNER JOIN HORAIRE ON HORAIRE.COURS=COURS.ID INNER JOIN SALLE ON SALLE.ID=HORAIRE.SALLE INNER 
  JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE SECTION.ABREVIATION='CA' AND SALLE.NIVEAU_ETUDE=2

 
   WHERE SECTION.ABREVIATION='CO' AND SALLE.NIVEAU_ETUDE=1
   select * from HORAIRE
   select * from AFFECTATION_COURS

  DELETE FROM HORAIRE
  DELETE FROM AFFECTATION_COURS
  delete from 

  SELECT * FROM HORAIRE






  EXEC SITUATION_TITULARISATIO 1,'CA','A'


  EXEC 

  ALTER PROC SITUATION_TITULARISATIO
  (@NIVEAU INT,@ABREVIATION VARCHAR(5),@LETTRE VARCHAR(1))
  AS

  SELECT TOP 1 SUBSTRING(CONCAT(NOM,' ',POSTNOM),1,18) ,DESIGNATION_SALLE.NOMBRE_PLACE,
  DESIGNATION_SALLE.NOMBRE_PLACE-(
  SELECT COUNT(*) FROM INSCRIPTION_ELEVE INNER JOIN DETAILS_INSCRIPTION ON DETAILS_INSCRIPTION.ID_INSCRIPTION=INSCRIPTION_ELEVE.ID
   AND ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE) INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=INSCRIPTION_ELEVE.SALLE INNER JOIN SALLE
   ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE SALLE.NIVEAU_ETUDE=@niveau AND SECTION.ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE
   ),
  SALLE.NIVEAU_ETUDE,SECTION.ABREVIATION,DESIGNATION_SALLE.LETTRE,
  COUNT(HORAIRE.ID),
  CONCAT(NIVEAU_ETUDE,'émè',ABREVIATION,'/',LETTRE)
  ,
  (
  SELECT COUNT(*) FROM INSCRIPTION_ELEVE INNER JOIN DETAILS_INSCRIPTION ON DETAILS_INSCRIPTION.ID_INSCRIPTION=INSCRIPTION_ELEVE.ID
   AND ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE) INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=INSCRIPTION_ELEVE.SALLE INNER JOIN SALLE
   ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE SALLE.NIVEAU_ETUDE=@niveau AND SECTION.ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE
   )
   
   FROM  AGENT INNER JOIN TITULARISATION_SALLE ON TITULARISATION_SALLE.AGENT
  =AGENT.MATRICULE INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=TITULARISATION_SALLE.SALLE
   INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE 
   inner join  SECTION ON SECTION.ID=SALLE.SECTION LEFT JOIN HORAIRE ON HORAIRE.SALLE=SALLE.ID AND
    HORAIRE.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE)  WHERE SALLE.NIVEAU_ETUDE=@niveau AND
   SECTION.ABREVIATION=@ABREVIATION  AND DESIGNATION_SALLE.LETTRE=@LETTRE AND TITULARISATION_SALLE.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE)  
    GROUP BY DESIGNATION_SALLE.ID ,NOMBRE_PLACE,AGENT.MATRICULE,AGENT.NOM,AGENT.POSTNOM,NIVEAU_ETUDE,LETTRE,ABREVIATION
  
  END

 
 EXEC NOUVEAU_TRAVAIL 1,'CO','B','2021MM0','JHJHH',12,'RELIGION'
ALTER PROC NOUVEAU_TRAVAIL
 (@NIVEAU INT,@ABREVIATION VARCHAR(5),@LETTRE VARCHAR(1),@PROF VARCHAR(10),@DESIGNATION VARCHAR(25),@MAXIMUN INT,@COURS VARCHAR(15))
 AS
 BEGIN
	declare @id_designation int;
	declare @id_cours int;
	select @id_designation= DESIGNATION_SALLE.ID from DESIGNATION_SALLE inner join SALLE on SALLE.ID=DESIGNATION_SALLE.ID_SALLE inner join SECTION on SECTION.ID=SALLE.SECTION WHERE SALLE.NIVEAU_ETUDE=@niveau AND SECTION.ABREVIATION=@ABREVIATION AND DESIGNATION_SALLE.LETTRE=@LETTRE
	SELECT @id_cours=ID FROM COURS WHERE COURS.DESIGNATION=@COURS
	insert into TRAVAIL(COURS,PROF,DENOMINATION,DESIGNATION_SALLE)VALUES(@id_cours,@PROF,@DESIGNATION,@id_designation)
	insert into DETAILS_TRAVAIL(ID,motif,MAXIMUM,ANNE,PERIODE)select ( SELECT MAX(ID) FROM TRAVAIL),1,@MAXIMUN,(select max(id) from ANNE_SCOLAIRE),(SELECT MAX(ID) FROM periode)
	INSERT INTO COTATION(ID_TRAVAIL,MATRICULE_ELEVE,POINT)SELECT ( SELECT MAX(ID) FROM TRAVAIL),MATRICULE,0 FROM LISTE_INSCRIT_JOURNALIER WHERE NIVEAU_ETUDE=@NIVEAU AND ABREVIATION=@ABREVIATION AND LETTRE=@LETTRE

 END

 SELECT DATE,HEURE,DENOMINATION,MAXIMUM FROM DETAILS_TRAVAIL INNER JOIN 
 TRAVAIL ON TRAVAIL.ID=DETAILS_TRAVAIL.ID INNER JOIN COURS on COURS.ID=TRAVAIL.COURS
  INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=TRAVAIL.DESIGNATION_SALLE INNER
   JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION WHERE SECTION.ABREVIATION='CO' AND COURS.DESIGNATION='' SALLE.NIVEAU_ETUDE=1 AND DESIGNATION_SALLE.LETTRE='B' AND DETAILS_TRAVAIL.PERIODE=(SELECT MAX(ID) FROM periode)



 SELECT * FROM TRAVAIL
 SELECT * FROM COTATION

 SELECT MATRICULE,UPPER(NOM),UPPER(POSTNOM),UPPER(PRENOM),POINT FROM COTATION INNER JOIN ELEVE ON ELEVE.MATRICULE=COTATION.MATRICULE_ELEVE WHERE DETAILS_COTATION.ID_COTATION=16
 SELECT MATRICULE,UPPER(NOM),UPPER(POSTNOM),UPPER(PRENOM),POINT FROM COTATION INNER JOIN ELEVE ON ELEVE.MATRICULE=COTATION.MATRICULE_ELEVE

 DELETE FROM DETAILS_TRAVAIL
 DELETE FROM TRAVAIL

 SELECT MATRICULE,NOM,POSTNOM,PRENOM,POINT FROM LISTE_INSCRIT_JOURNALIER WHERE NIVEAU_ETUDE=1 AND ABREVIATION='CO'
  AND LETTRE='A'

  SELECT * FROM COTATION

  UPDATE COTATION SET POINT=2 WHERE ID_TRAVAIL=18 AND MATRICULE_ELEVE='2021MM0001'
  SELECT * FROM COTATION

  CREATE PROC COTER
  (@POINT INT,@ID INT,@MATRICULE VARCHAR(10))
  AS
  BEGIN
	UPDATE COTATION SET POINT=@POINT WHERE MATRICULE_ELEVE=@MATRICULE AND ID_TRAVAIL=@ID
  END

   CREATE PROC COTER_UNIQUE
  (@POINT INT,@ID INT,@MATRICULE VARCHAR(10))
  AS
  BEGIN
	UPDATE COTATION SET POINT=@POINT WHERE ID_TRAVAIL=@ID
  END

     ALTER PROC ANNULER_INTERRO
  (@ID INT)
  AS
  BEGIN
  DELETE FROM DETAILS_TRAVAIL WHERE DETAILS_TRAVAIL.ID=@ID
    DELETE FROM COTATION WHERE COTATION.ID_TRAVAIL=@ID
	DELETE FROM TRAVAIL WHERE TRAVAIL.ID=@ID
  END


  SELECT * FROM COTATION
  SELECT * FROM TRAVAIL
  select * from TRAVAIL
  select * from DETAILS_TRAVAIL


  SELECT ELEVE.MATRICULE,NOM,POSTNOM,PRENOM, CONCAT(SUM(POINT),'/',SUM(DETAILS_TRAVAIL.MAXIMUM)) AS COTE FROM ELEVE  LEFT JOIN COTATION ON COTATION.MATRICULE_ELEVE=ELEVE.MATRICULE 
  LEFT JOIN TRAVAIL ON TRAVAIL.ID=COTATION.ID_TRAVAIL LEFT JOIN DETAILS_TRAVAIL ON DETAILS_TRAVAIL.ID=TRAVAIL.ID
 LEFT JOIN COURS ON COURS.ID=TRAVAIL.COURS LEFT JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=TRAVAIL.DESIGNATION_SALLE
  LEFT JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE LEFT JOIN SECTION ON SECTION.ID=SALLE.SECTION
   WHERE DETAILS_TRAVAIL.PERIODE=(SELECT MAX(ID) FROM periode) AND COURS.DESIGNATION='FRANCAIS' AND SALLE.NIVEAU_ETUDE=1 AND SECTION.ABREVIATION='CO' AND DESIGNATION_SALLE.LETTRE='A' GROUP BY ELEVE.MATRICULE,NOM,POSTNOM,PRENOM

    SELECT ELEVE.MATRICULE,NOM,POSTNOM,PRENOM, SUM(POINT) AS COTE FROM ELEVE  LEFT JOIN COTATION ON COTATION.MATRICULE_ELEVE=ELEVE.MATRICULE 
	 LEFT JOIN TRAVAIL ON TRAVAIL.ID=COTATION.ID_TRAVAIL LEFT JOIN DETAILS_TRAVAIL ON DETAILS_TRAVAIL.ID=TRAVAIL.ID
 LEFT JOIN COURS ON COURS.ID=TRAVAIL.COURS AND  COURS.DESIGNATION='FRANCAIS'  LEFT JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=TRAVAIL.DESIGNATION_SALLE  AND DESIGNATION_SALLE.LETTRE='A'
   LEFT JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE  AND SALLE.NIVEAU_ETUDE=1 LEFT JOIN SECTION ON SECTION.ID=SALLE.SECTION  AND SECTION.ABREVIATION='CO'
  WHERE DETAILS_TRAVAIL.PERIODE=(SELECT MAX(ID) FROM periode) 
	 GROUP BY ELEVE.MATRICULE,NOM,POSTNOM,PRENOM


	 alter PROC AFFECTATION_BULLETION
	 (@COURS VARCHAR(10),@NIVEAU INT,@ABREVIATION VARCHAR(5),@LETTRE VARCHAR(1))
	 AS
	 BEGIN
		
		
				DECLARE @i int = 1;
				WHILE(@i <= (select count(*) from LISTE_INSCRIT_JOURNALIER where NIVEAU_ETUDE=@NIVEAU and ABREVIATION=@ABREVIATION and LETTRE=@LETTRE))
				BEGIN
				delete from BULLETIN where MATRICULE_ELEVE=(select top 1 BULLETIN.MATRICULE_ELEVE from BULLETIN 
				inner join LISTE_INSCRIT_JOURNALIER on LISTE_INSCRIT_JOURNALIER.MATRICULE=BULLETIN.MATRICULE_ELEVE
				 where BULLETIN.COURS=(select id from COURS where COURS.DESIGNATION=@COURS) and
				  PERIODE=(select max(PERIODE.id) from periode) and
				  ANNE=(select max(ANNE_SCOLAIRE.ID) from ANNE_SCOLAIRE) and  NIVEAU_ETUDE=@NIVEAU and ABREVIATION=@ABREVIATION and LETTRE=@LETTRE
				  )
				  
				SET @i = @i+1
				END
		
		INSERT INTO BULLETIN (MATRICULE_ELEVE,PERIODE,COURS,POINT,ANNE)
		SELECT ELEVE.MATRICULE,(SELECT MAX(ID) FROM periode),COURS.ID,SUM(POINT)*HORAIRE.PONDERATION/SUM(DETAILS_TRAVAIL.MAXIMUM),
	   (SELECT MAX(ID) FROM ANNE_SCOLAIRE) FROM ELEVE  LEFT JOIN COTATION ON COTATION.MATRICULE_ELEVE=ELEVE.MATRICULE   INNER JOIN
	    TRAVAIL ON TRAVAIL.ID=COTATION.ID_TRAVAIL INNER JOIN DETAILS_TRAVAIL ON DETAILS_TRAVAIL.ID=TRAVAIL.ID INNER JOIN COURS ON 
		COURS.ID=TRAVAIL.COURS INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=TRAVAIL.DESIGNATION_SALLE  INNER JOIN SALLE ON 
		SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION  INNER JOIN HORAIRE ON HORAIRE.COURS=COURS.ID
		 WHERE DETAILS_TRAVAIL.PERIODE=(SELECT MAX(ID) FROM periode) AND COURS.DESIGNATION=@COURS AND SALLE.NIVEAU_ETUDE=@NIVEAU AND
		  SECTION.ABREVIATION=@ABREVIATION AND DESIGNATION_SALLE.LETTRE=@LETTRE AND HORAIRE.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE)
		   GROUP BY ELEVE.MATRICULE,NOM,POSTNOM,PRENOM,PONDERATION,COURS.ID
	 END
	   
	   SELECT * FROM LISTE_INSCRIT_JOURNALIER order by nom desc
	SELECT * from BULLETIN

	SELECT * FROM SANCTION
	SELECT * FROM DETAILS_SANCTION

	delete from BULLETIN where MATRICULE_ELEVE= (SELECT TOP 1 BULLETIN.MATRICULE_ELEVE FROM BULLETIN)
