using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace ECOLE_SECONDAIRE.DESIGN_USER_CONTROL
{
    public partial class AFFECTATION_RESULTAT : UserControl
    {

        CLASS_DATA_BASE.CLS_GLOSSIERE A = new CLASS_DATA_BASE.CLS_GLOSSIERE();
        CLASS_DATA_BASE.AJOUT B = new CLASS_DATA_BASE.AJOUT();

        public string CHARGEMENT_NIVEAU = "SELECT NIVEAU_ETUDE FROM SALLE_DE_CLASS GROUP BY NIVEAU_ETUDE";
        public AFFECTATION_RESULTAT()
        {
            InitializeComponent();
            A.CHARGE_COMBO(NIVEAU, "" + CHARGEMENT_NIVEAU);
          
        }

        private void NIVEAU_SelectedIndexChanged(object sender, EventArgs e)
        {
            ABREVIATION.Enabled = true;
            ABREVIATION.Items.Clear();
            string SESSION = "SELECT ABREVIATION FROM SALLE_DE_CLASS WHERE NIVEAU_ETUDE=" + NIVEAU.SelectedItem.ToString() + " GROUP BY ABREVIATION";
            A.CHARGE_COMBO(ABREVIATION, "" + SESSION);
        }

        private void AFFECTATION_SelectedIndexChanged(object sender, EventArgs e)
        {
            DESIGNATION.Enabled = true;
            DESIGNATION.Items.Clear();
            string SESSION = "SELECT LETTRE FROM SALLE_DE_CLASS WHERE NIVEAU_ETUDE=" + NIVEAU.SelectedItem.ToString() + " AND ABREVIATION='" + ABREVIATION.SelectedItem.ToString() + "'";
            A.CHARGE_COMBO(DESIGNATION, "" + SESSION);
        }

        private void DESIGNATION_SelectedIndexChanged(object sender, EventArgs e)
        {
            COMBO_COURS.Items.Clear();
           // A.LABEL(NOMBRE_COURS, "SELECT COUNT(COURS_SALLE.DESIGNATION) FROM COURS_SALLE WHERE NIVEAU_ETUDE=" + NIVEAU.SelectedItem.ToString() + " AND ABREVIATION='" + ABREVIATION.SelectedItem.ToString() + "' AND LETTRE='" + DESIGNATION.SelectedItem.ToString() + "'", 0);
            A.CHARGE_COMBO(COMBO_COURS, "SELECT COURS_SALLE.DESIGNATION FROM COURS_SALLE WHERE NIVEAU_ETUDE=" + NIVEAU.SelectedItem.ToString() + " AND ABREVIATION='" + ABREVIATION.SelectedItem.ToString() + "' AND LETTRE='" + DESIGNATION.SelectedItem.ToString() + "'");
            COMBO_COURS.Enabled = true;
        }

        private void COMBO_COURS_SelectedIndexChanged(object sender, EventArgs e)
        {
            guna2Button1.Enabled = true;
            dataGridView1.DataSource = A.TABLEAU("  SELECT ELEVE.MATRICULE,NOM,POSTNOM,PRENOM, CONCAT(SUM(POINT),'/',SUM(DETAILS_TRAVAIL.MAXIMUM)) AS COTE,CONCAT(SUM(POINT)*HORAIRE.PONDERATION/SUM(DETAILS_TRAVAIL.MAXIMUM),'/',HORAIRE.PONDERATION) AS APPERCU FROM ELEVE  LEFT JOIN COTATION ON COTATION.MATRICULE_ELEVE=ELEVE.MATRICULE   INNER JOIN TRAVAIL ON TRAVAIL.ID=COTATION.ID_TRAVAIL INNER JOIN DETAILS_TRAVAIL ON DETAILS_TRAVAIL.ID=TRAVAIL.ID INNER JOIN COURS ON COURS.ID=TRAVAIL.COURS INNER JOIN DESIGNATION_SALLE ON DESIGNATION_SALLE.ID=TRAVAIL.DESIGNATION_SALLE  INNER JOIN SALLE ON SALLE.ID=DESIGNATION_SALLE.ID_SALLE INNER JOIN SECTION ON SECTION.ID=SALLE.SECTION  INNER JOIN HORAIRE ON HORAIRE.COURS=COURS.ID  WHERE DETAILS_TRAVAIL.PERIODE=(SELECT MAX(ID) FROM periode) AND COURS.DESIGNATION='" + COMBO_COURS.SelectedItem + "' AND SALLE.NIVEAU_ETUDE=" + NIVEAU.SelectedItem + " AND SECTION.ABREVIATION='" + ABREVIATION.SelectedItem + "' AND DESIGNATION_SALLE.LETTRE='" + DESIGNATION.SelectedItem + "' AND HORAIRE.ANNE=(SELECT MAX(ID) FROM ANNE_SCOLAIRE) GROUP BY ELEVE.MATRICULE,NOM,POSTNOM,PRENOM,PONDERATION");
            dataGridView2.DataSource = A.TABLEAU("SELECT BULLETIN.MATRICULE_ELEVE AS MATRICULE,NOM,POSTNOM,PRENOM,POINT FROM BULLETIN INNER JOIN LISTE_INSCRIT_JOURNALIER ON LISTE_INSCRIT_JOURNALIER.MATRICULE=BULLETIN.MATRICULE_ELEVE INNER JOIN COURS ON COURS.ID=BULLETIN.COURS WHERE  COURS.DESIGNATION='" + COMBO_COURS.SelectedItem + "' AND NIVEAU_ETUDE=" + NIVEAU.SelectedItem + " AND ABREVIATION='" + ABREVIATION.SelectedItem + "' AND LETTRE='" + DESIGNATION.SelectedItem + "'  AND BULLETIN.PERIODE=(SELECT MAX(ID) FROM PERIODE)");
            A.LABEL(label21, "SELECT COUNT(*) FROM BULLETIN INNER JOIN LISTE_INSCRIT_JOURNALIER ON LISTE_INSCRIT_JOURNALIER.MATRICULE=BULLETIN.MATRICULE_ELEVE INNER JOIN COURS ON COURS.ID=BULLETIN.COURS WHERE  COURS.DESIGNATION='" + COMBO_COURS.SelectedItem + "' AND NIVEAU_ETUDE=" + NIVEAU.SelectedItem + " AND ABREVIATION='" + ABREVIATION.SelectedItem + "' AND LETTRE='" + DESIGNATION.SelectedItem + "'",0);
            A.LABEL(label8, "  SELECT PONDERATION FROM COURS_SALLE WHERE NIVEAU_ETUDE=" + NIVEAU.SelectedItem + " AND LETTRE='" + DESIGNATION.SelectedItem + "' AND ABREVIATION='" + ABREVIATION.SelectedItem + "' AND DESIGNATION='"+COMBO_COURS.SelectedItem+"'", 0);
        }

        private void guna2Button1_Click(object sender, EventArgs e)
        {
            A.EXEC_UNIVERSEL("AFFECTATION_BULLETION", "'"+COMBO_COURS.SelectedItem+"',"+NIVEAU.SelectedItem+",'"+ABREVIATION.SelectedItem+"','"+DESIGNATION.SelectedItem+"'", "COTATION");
            richTextBox2.Text="'" + COMBO_COURS.SelectedItem + "'," + NIVEAU.SelectedItem + ",'" + ABREVIATION.SelectedItem + "','" + DESIGNATION.SelectedItem + "'";
        }

     
    }
}
